[package]
name = "mirror-intel"
version = "0.1.0"
authors = ["Alex Chi <iskyzh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { git ="https://github.com/SergioBenitez/Rocket" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket"}
rusoto_core = "0.45.0"
rusoto_s3 = "0.45.0"
thiserror = "1.0"
reqwest = { version = "0.10", features = ["stream"] }
tokio = { version = "0.2", features = ["full"] }
lazy_static = "1.4"
slog-term = "2.6"
slog = "2.5"
slog-async = "2.5"
futures-util = "0.3"
futures = "0.3"
bytes = "0.6"
slog-envlogger = "2.2"
tokio-util = "0.3"
serde = "1.0"
